# Generated by Django 4.0.3 on 2022-06-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('idadmin', models.AutoField(db_column='idAdmin', primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'administrador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('idarea', models.AutoField(db_column='idArea', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo', models.CharField(db_column='tipo', max_length=50)),
                ('nombre', models.CharField(db_column='nombre', max_length=50)),
            ],
            options={
                'db_table': 'area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatosAlgoritmo',
            fields=[
                ('idreg', models.AutoField(db_column='idReg', primary_key=True, serialize=False)),
                ('casospos', models.IntegerField(db_column='casospos')),
                ('casosneg', models.IntegerField(db_column='casosneg')),
                ('fecha', models.DateField(db_column='fecha')),
            ],
            options={
                'db_table': 'datos_algoritmo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiaLaboral',
            fields=[
                ('iddialaboral', models.AutoField(db_column='idDiaLaboral', primary_key=True, serialize=False)),
                ('dia', models.CharField(blank=True, max_length=100, null=True)),
                ('horaentrada', models.TimeField(blank=True, db_column='horaEntrada', null=True)),
            ],
            options={
                'db_table': 'dia_laboral',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idempleado', models.AutoField(db_column='idEmpleado', primary_key=True, serialize=False)),
                ('correo', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('fechanacimiento', models.DateField(blank=True, db_column='fechaNacimiento', null=True)),
                ('sexo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('idempresa', models.AutoField(db_column='idEmpresa', primary_key=True, serialize=False)),
                ('nombregenerado', models.CharField(blank=True, db_column='nombreGenerado', max_length=50, null=True, unique=True)),
                ('clave', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FormularioDiario',
            fields=[
                ('idformulariodiario', models.AutoField(db_column='idFormularioDiario', primary_key=True, serialize=False)),
                ('fechahora', models.DateTimeField()),
                ('estaemba', models.CharField(max_length=50)),
                ('mesesemb', models.CharField(max_length=50)),
                ('fiebre', models.CharField(max_length=50)),
                ('tos', models.CharField(max_length=50)),
                ('odinogia', models.CharField(max_length=50)),
                ('disnea', models.CharField(max_length=50)),
                ('irritabi', models.CharField(max_length=50)),
                ('diarrea', models.CharField(max_length=50)),
                ('dotoraci', models.CharField(max_length=50)),
                ('calofrios', models.CharField(max_length=50)),
                ('cefalea', models.CharField(max_length=50)),
                ('mialgias', models.CharField(max_length=50)),
                ('artral', models.CharField(max_length=50)),
                ('rinorrea', models.CharField(max_length=50)),
                ('polipnea', models.CharField(max_length=50)),
                ('vomito', models.CharField(max_length=50)),
                ('dolabdo', models.CharField(max_length=50)),
                ('conjun', models.CharField(max_length=50)),
                ('cianosis', models.CharField(max_length=50)),
                ('inisubis', models.CharField(max_length=50)),
                ('conocaso', models.CharField(max_length=50)),
                ('contaves', models.CharField(max_length=50)),
                ('concerdo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'formulario_diario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FormularioSalud',
            fields=[
                ('idformulariosalud', models.AutoField(db_column='idFormulario_salud', primary_key=True, serialize=False)),
                ('diabetes', models.CharField(max_length=50)),
                ('epoc', models.CharField(max_length=50)),
                ('asma', models.CharField(max_length=50)),
                ('inmusupr', models.CharField(max_length=50)),
                ('hiperten', models.CharField(max_length=50)),
                ('vihsida', models.CharField(max_length=50)),
                ('otracon', models.CharField(max_length=50)),
                ('enfcardi', models.CharField(max_length=50)),
                ('obesidad', models.CharField(max_length=50)),
                ('insrencr', models.CharField(max_length=50)),
                ('tabaquis', models.CharField(max_length=50)),
                ('vacunado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'formulario_salud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReporteDeContagio',
            fields=[
                ('idreportedecontagio', models.IntegerField(db_column='idReporteDeContagio', primary_key=True, serialize=False)),
                ('respuesta', models.CharField(blank=True, max_length=300, null=True)),
                ('fechahora', models.DateTimeField()),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'reporte_de_contagio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReporteDeFalta',
            fields=[
                ('idreportedefalta', models.AutoField(db_column='idReporteDeFalta', primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('fechainiciofalta', models.DateField(blank=True, db_column='fechaInicioFalta', null=True)),
                ('fechafinfalta', models.DateField(blank=True, db_column='fechaFinFalta', null=True)),
                ('comentario', models.CharField(blank=True, max_length=300, null=True)),
                ('fechahora', models.DateTimeField()),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'reporte_de_falta',
                'managed': False,
            },
        ),
    ]
