# Generated by Django 4.0.4 on 2022-04-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('idadmin', models.AutoField(db_column='idAdmin', primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=50)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'administrador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('idarea', models.AutoField(db_column='idArea', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('clavegenerada', models.CharField(db_column='claveGenerada', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contiene',
            fields=[
                ('idarea', models.IntegerField(db_column='idArea', db_index=True, primary_key=True, serialize=False)),
                ('idempleado', models.IntegerField(db_column='idEmpleado', db_index=True)),
            ],
            options={
                'db_table': 'contiene',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiaLaboral',
            fields=[
                ('iddialaboral', models.AutoField(db_column='idDiaLaboral', primary_key=True, serialize=False)),
                ('dia', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'dia_laboral',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DireccionEmpleado',
            fields=[
                ('iddireccionempleado', models.AutoField(db_column='idDireccionEmpleado', primary_key=True, serialize=False)),
                ('calle', models.CharField(blank=True, max_length=50, null=True)),
                ('colonia', models.CharField(blank=True, max_length=50, null=True)),
                ('codpostal', models.CharField(blank=True, db_column='codPostal', max_length=50, null=True)),
                ('delegacion', models.CharField(blank=True, max_length=50, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'direccion_empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DireccionEmpresa',
            fields=[
                ('iddireccionempresa', models.AutoField(db_column='idDireccionEmpresa', primary_key=True, serialize=False)),
                ('calle', models.CharField(blank=True, max_length=50, null=True)),
                ('colonia', models.CharField(blank=True, max_length=50, null=True)),
                ('codpostal', models.CharField(blank=True, db_column='codPostal', max_length=50, null=True)),
                ('delegacion', models.CharField(blank=True, max_length=50, null=True)),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'direccion_empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idempleado', models.AutoField(db_column='idEmpleado', primary_key=True, serialize=False)),
                ('correo', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('horaentrada', models.TimeField(blank=True, db_column='horaEntrada', null=True)),
                ('riesgo', models.PositiveIntegerField(blank=True, null=True)),
                ('fechanacimiento', models.DateField(blank=True, db_column='fechaNacimiento', null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('sexo', models.CharField(blank=True, max_length=50, null=True)),
                ('respuestaformulariosalud', models.JSONField(blank=True, db_column='respuestaFormularioSalud', null=True)),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('idempresa', models.AutoField(db_column='idEmpresa', primary_key=True, serialize=False)),
                ('nombregenerado', models.CharField(blank=True, db_column='nombreGenerado', max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FormularioDiario',
            fields=[
                ('idformulariodiario', models.AutoField(db_column='idFormularioDiario', primary_key=True, serialize=False)),
                ('fecha', models.CharField(max_length=50)),
                ('hora', models.CharField(max_length=50)),
                ('respuesta', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'formulario_diario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NombreAdministrador',
            fields=[
                ('idnombreadmin', models.AutoField(db_column='idNombreAdmin', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('appaterno', models.CharField(db_column='apPaterno', max_length=50)),
                ('apmaterno', models.CharField(db_column='apMaterno', max_length=50)),
            ],
            options={
                'db_table': 'nombre_administrador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NombreEmpleado',
            fields=[
                ('idnombreempleado', models.AutoField(db_column='idNombreEmpleado', primary_key=True, serialize=False)),
                ('primernombre', models.IntegerField(blank=True, db_column='primerNombre', null=True)),
                ('appaterno', models.IntegerField(blank=True, db_column='apPaterno', null=True)),
                ('apmaterno', models.IntegerField(blank=True, db_column='apMaterno', null=True)),
            ],
            options={
                'db_table': 'nombre_empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NombreEmpresa',
            fields=[
                ('idnombreempresa', models.IntegerField(db_column='idNombreEmpresa', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'nombre_empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReporteDeContagio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idreportedecontagio', models.IntegerField(blank=True, db_column='idReporteDeContagio', null=True)),
                ('fecha', models.IntegerField(blank=True, null=True)),
                ('hora', models.IntegerField(blank=True, null=True)),
                ('respuesta', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reporte_de_contagio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReporteDeFalta',
            fields=[
                ('idreportedefalta', models.AutoField(db_column='idReporteDeFalta', primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('fechainiciofalta', models.DateField(blank=True, db_column='fechaInicioFalta', null=True)),
                ('fechafinfalta', models.DateField(blank=True, db_column='fechaFinFalta', null=True)),
                ('comentario', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'reporte_de_falta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('idtransporte', models.AutoField(db_column='idTransporte', primary_key=True, serialize=False)),
                ('tipo', models.IntegerField()),
                ('entrada', models.IntegerField()),
                ('salida', models.IntegerField()),
                ('horaentrada', models.IntegerField(db_column='horaEntrada')),
            ],
            options={
                'db_table': 'transporte',
                'managed': False,
            },
        ),
    ]
