# Generated by Django 4.0.4 on 2022-04-25 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0003_eliminaresprueba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EliminarEsPrueba',
        ),
    ]
