# Generated by Django 4.0.4 on 2022-04-27 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0004_delete_eliminaresprueba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NombreEmpleado',
        ),
    ]
