# Generated by Django 4.0.3 on 2022-05-10 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0006_nombreempleado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DireccionEmpresa',
        ),
        migrations.DeleteModel(
            name='Transporte',
        ),
    ]
