# Generated by Django 4.0.3 on 2022-05-10 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0007_delete_direccionempresa_delete_transporte'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NombreEmpleado',
        ),
    ]
