# Generated by Django 4.0.3 on 2022-05-11 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0008_delete_nombreempleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioSalud',
            fields=[
                ('idformulariosalud', models.AutoField(db_column='idFormularioSalud', primary_key=True, serialize=False)),
                ('diabetes', models.CharField(max_length=50)),
                ('epoc', models.CharField(max_length=50)),
                ('asma', models.CharField(max_length=50)),
                ('inmusupr', models.CharField(max_length=50)),
                ('hiperten', models.CharField(max_length=50)),
                ('vihsida', models.CharField(max_length=50)),
                ('otracon', models.CharField(max_length=50)),
                ('enfcardi', models.CharField(max_length=50)),
                ('obesidad', models.CharField(max_length=50)),
                ('insrencr', models.CharField(max_length=50)),
                ('tabaquis', models.CharField(max_length=50)),
                ('conanima', models.CharField(max_length=50)),
                ('vacunado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'formulario_salud',
                'managed': False,
            },
        ),
    ]
