# Generated by Django 4.0.3 on 2022-05-17 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0009_formulariosalud'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NombreEmpresa',
        ),
    ]
