# Generated by Django 4.0.3 on 2022-05-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0010_delete_nombreempresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosAlgoritmo',
            fields=[
                ('idreg', models.AutoField(db_column='idReg', primary_key=True, serialize=False)),
                ('casospos', models.IntegerField(db_column='casospos')),
                ('casosneg', models.IntegerField(db_column='casosneg')),
                ('fecha', models.DateField(db_column='fecha')),
            ],
            options={
                'db_table': 'datos_algoritmo',
                'managed': False,
            },
        ),
    ]
