# Generated by Django 4.0.3 on 2022-05-30 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0011_datosalgoritmo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DireccionEmpleado',
        ),
    ]
