# Generated by Django 4.0.3 on 2022-06-03 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0012_delete_direccionempleado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contiene',
        ),
        migrations.DeleteModel(
            name='NombreAdministrador',
        ),
    ]
